name: Publish
on: [workflow_dispatch]
jobs:
  # publishing azure artifacts
  azure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
      - run: yarn install
      - name: "Version and publish" # Interesting step
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "vikas@cldcvr.com"
          yarn update-packages
          git add -A
          git commit -m "Icons updated by GithubActions"
          yarn publish-packages